### PR TITLE
Enhanced the website design and user experience

### LINKED ISSUE #2: [Style] Enhance the website design and user experience
### What's the style idea?

Enhance the website's user interface by improving its design, layout, and overall user experience for better aesthetics and usability.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Eventica/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Eventica/blob/main/.github/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by wildcraft958**
# Fixes Issue🛠️

Closes #2

# Description👨‍💻

1. The event section cards needed to be changed first. Their design was too simple, and for some events, there was no clear distinction between the card and the background. Made all necessary changes.
2. Added a hover effect for nav links would look good like one cyan color underlines fade-in fade-out effect.

# Type of Change📄

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Style (non-breaking change which improves website style or formatting)

# Checklist✅

- [ ] I am an Open Source contributor
- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Can we implement the same or similar design for upcoming events cards also, make the new commits in this same PR @wildcraft958

**Comment by Rakesh9100** [comment]
The Register button is not shown now in upcoming events card, please fix and make the new commits in this same PR @wildcraft958

**Comment by wildcraft958** [comment]
okay let me check once

**Comment by Rakesh9100** [comment]
Any update on this PR @wildcraft958

**Comment by wildcraft958** [comment]
is it working now?

**Pull request merged**
